version: '3'

services:
  app:
    container_name: wwp_app
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/wwp
    depends_on:
      - 'postgres'
      - 'webpack'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create db:migrate db:seed && bundle exec rails s -p 3000 -b '0.0.0.0'"

  webpack:
    container_name: wwp_webpack
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/wwp
    command: bash -c "./bin/webpack-dev-server"

  postgres:
    container_name: wwp_db
    image: 'postgres:10'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
