version: 2.1

orbs:
  heroku: circleci/heroku@1.0.0

jobs:
  build:
    machine: true
    working_directory: ~/app # TODO: remove?
    environment:
      APP_PORT: 3000
    steps:
      - checkout
      - run:
          name: Start containers
          command: docker-compose up -d
      - run:
          name: Run tests
          command: docker-compose exec app rspec

  deploy-staging:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: staging-wwp
      - run:
          name: Migrate db
          command: |
            heroku run rails db:migrate --app staging-wwp --exit-code
            heroku run rails db:seed --app staging-wwp
            heroku restart --app staging-wwp

workflows:
  version: 2.1
  build-n-deploy:
    jobs:
      - build
          filters:
            branches:
              only: master
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: staging
