version: 2
jobs:
  build:
    machine: true
    working_directory: ~/app
    environment:
      APP_PORT: 3000

    steps:
      - checkout

      - run:
          name: Start containers
          command: docker-compose up -d

      - run:
          name: Run tests
          command: docker-compose exec app rspec

      - deploy:
          name: Deploy to staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              git push git@heroku.com:staging-wwp.git $CIRCLE_SHA1:refs/heads/master
              heroku run rails db:migrate --app staging-wwp --exit-code
              heroku run rails db:seed --app staging-wwp
              heroku restart --app staging-wwp
            fi

      - deploy:
          name: Deploy to production
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              git push git@heroku.com:wwp.git $CIRCLE_SHA1:refs/heads/master
              heroku run rails db:migrate --app wwp --exit-code
              heroku run rails db:seed --app wwp
              heroku restart --app wwp
            fi
